Repository AdamLesage/area-epitech, pull requests merged in 2024-12, with the labels that each got.

#93 GitHub service reaction
  .github/workflows/main.yml
  README.md
  backend/app.js
  backend/authentication/passport.js
  backend/package.json
  backend/prisma/migrations/20241204122724_auth_tokens_cannot_be_null/migration.sql
  backend/prisma/migrations/20241209130008_service_columns_are_unique/migration.sql
  backend/prisma/migrations/20241209160306_change_linked_account_table/migration.sql
  backend/prisma/migrations/20241210121921_add_username_column_in_linked_accounts_table/migration.sql
  backend/prisma/schema.prisma
  backend/routes/authentication.js
  backend/routes/authentication.test.js
  backend/routes/user.js
  backend/routes/user.test.js
  backend/services/githubService.js
Labels: enhancement, server

#106 Add User store
  backend/routes/user.js
  frontend/src/stores/users.ts
  frontend/src/views/DashboardPage.vue
  frontend/src/views/LoginPage.vue
  frontend/src/views/SignUpPage.vue
  frontend/src/views/UserDetailsPage.vue
  frontend/src/views/UserInfoPage.vue
Labels: enhancement, web client, mobile client

#107 Home about page
  frontend/src/assets/svg/Timeline.svg
  frontend/src/assets/svg/Timelinewithbackground.svg
  frontend/src/router/index.ts
  frontend/src/views/AboutUsPage.vue
  frontend/src/views/HomePage.vue
  frontend/src/views/LoginPage.vue
  frontend/src/views/SignUpPage.vue
Labels: UI/UX

#111 109 create webapp creation area page
  frontend/src/components/AREACreationComponent.vue
  frontend/src/components/NavbarComponent.vue
  frontend/src/router/index.ts
  frontend/src/views/AboutUsPage.vue
  frontend/src/views/MyAreaPage.vue
Labels: UI/UX, web client

#119 Area users
  backend/routes/user.js
  frontend/src/views/MyAreaPage.vue
Labels: enhancement

#118 More doc for mvp
  README.md
  documentation/MODELS.md
  documentation/ROUTES.md
Labels: documentation

#125 Area deployment
  backend/routes/ActionReaction.js
  backend/services/githubService.js
Labels: fix bug

#130 Small fixes
  backend/services/services-info.json
  frontend/src/components/AREACreationComponent.vue
  frontend/src/components/NavbarComponent.vue
  frontend/src/views/AboutUsPage.vue
  frontend/src/views/DashboardPage.vue
  frontend/src/views/MyAreaPage.vue
Labels: fix bug

#129 More doc for mvp
  README.md
  documentation/ROUTES_FRONT.md
Labels: documentation

#131 feat(Github OAuth2 connexion): create linked account
  backend/routes/authentication.js
Labels: fix bug

#134 tests(API tests): change tests for routes backend
  backend/routes/action-reaction.test.js
  backend/routes/authentication.test.js
  backend/routes/user.test.js
Labels: tests

#142 fix (Mobile App) : Added a fix that makes the webapp accessible from …
  frontend/capacitor.config.ts
Labels: enhancement, mobile client
